version: '3.8'

services:
  # Frontend React Application
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000/api
      - REACT_APP_ML_API_URL=http://localhost:5000
    depends_on:
      - backend
      - ml-service
    volumes:
      - ./frontend:/app
      - /app/node_modules

  # Laravel Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_CONNECTION=mysql
      - DB_HOST=database
      - DB_PORT=3306
      - DB_DATABASE=telehealth
      - DB_USERNAME=root
      - DB_PASSWORD=password
      - ML_SERVICE_URL=http://ml-service:5000
    depends_on:
      - database
    volumes:
      - ./backend:/var/www/html

  # Python ML Service
  ml-service:
    build:
      context: ./ml-service
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - MODEL_PATH=/app/models
    volumes:
      - ./ml-service:/app

  # MySQL Database
  database:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=telehealth
    volumes:
      - mysql_data:/var/lib/mysql

  # Redis for caching and sessions
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  mysql_data: